{% set version = '1.22.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-r.oo
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/R.oo_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/R.oo/R.oo_{{ version }}.tar.gz
  sha256: c0862e4608fb2b8f91ec4494d46c2f3ba7bc44999f9aa3d7b9625d3792e7dd4c

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0
  noarch: generic

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: tools
requirements:
  build:
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-r.methodss3 >=1.7.1

  run:
    - r-base
    - r-r.methodss3 >=1.7.1

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('R.oo')"           # [not win]
    - "\"%R%\" -e \"library('R.oo')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/HenrikBengtsson/R.oo
  license: LGPL (>= 2.1)
  summary: Methods and classes for object-oriented programming in R with or without references.  Large
    effort has been made on making definition of methods as simple as possible with
    a minimum of maintenance for package developers.  The package has been developed
    since 2001 and is now considered very stable.  This is a cross-platform package
    implemented in pure R that defines standard S3 classes without any tricks.
  license_family: LGPL
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/LGPL-2.1'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: R.oo
# Version: 1.22.0
# Depends: R (>= 2.13.0), R.methodsS3 (>= 1.7.1)
# Imports: methods, utils
# Suggests: tools
# Date: 2018-04-21
# Title: R Object-Oriented Programming with or without References
# Authors@R: c(person("Henrik", "Bengtsson", role=c("aut", "cre", "cph"), email = "henrikb@braju.com"))
# Author: Henrik Bengtsson [aut, cre, cph]
# Maintainer: Henrik Bengtsson <henrikb@braju.com>
# Description: Methods and classes for object-oriented programming in R with or without references.  Large effort has been made on making definition of methods as simple as possible with a minimum of maintenance for package developers.  The package has been developed since 2001 and is now considered very stable.  This is a cross-platform package implemented in pure R that defines standard S3 classes without any tricks.
# License: LGPL (>= 2.1)
# LazyLoad: TRUE
# URL: https://github.com/HenrikBengtsson/R.oo
# BugReports: https://github.com/HenrikBengtsson/R.oo/issues
# NeedsCompilation: no
# Packaged: 2018-04-22 00:03:47 UTC; hb
# Repository: CRAN
# Date/Publication: 2018-04-22 03:23:04 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
