travis:
  secure:
    BINSTAR_TOKEN: YG2JhJ1yXEwaFG1CKpxBnMwUgF/EysnyjHP76Nk0g45aFBA3IWmyQw0dezVyeUr98b5SfoRICfIxqpf/qTxvfWAOzYl8rBv2cI9WbY97wTUD2m/hXPhl5Coe5KBX104sqdlWHp2duIADk6Shwd82Z7657Qtiq24S9HDHYZVwMYO6zIOz54a/atZGaZQXIE/CmA0oDVZ3YTspf8gbtBfRG22DrfowwUI+nFA/fAF9ZqJZhzOZ4sOe2uq7zdDFhnvJl7l21eVjCNMO1SWudLhgeyn0fTn1PkS/LfAeJwaF2pndhEYPgXN30hkczBIGy+auQNTLB3ZZupFrdmPcl9UsQFVA2U1pOmxZxcWly+2Lg4Rb150AWMgm29+31lNgeuIujSqVfMFe2faLrfE3Ml0JbSds78V6Hy+JCA+zUAEJ/8hBaCYd3iaBwU4h4fHjGoWOPnq2uEPBDHVkjyvTaTTU3HjXiQO6jUNw1lzPnRWs+cqrZ1bJ5ETJnvkLf4c6E6oNQWOId8QYNbnqudN2Skh+wp0uXXwUlWezsCOmjWxyL3XgRZmga8IZqKWlZRmlMfah+T37ZiZ2x1ZYLZkgLYWBpCOxiKipZN2+wg4fWQik15ELs4jXjPYoC0Bhc23Rv6TRo1AvoxAt2BudvlxeEwJmEzWeQrDkATRJ1aJXn4D5+rU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
