travis:
  secure:
    BINSTAR_TOKEN: ZUYyOtB4Lix1wSRcBSbFalIUszvG9UCqij7H/LrZy+YV6FX31eI/jV8nJBH3zLu6vLQOWBlRVToeJPcwhnDPbqToShBk6EL1/4WNmWRQo97nO1ZZpNe+Oxam5MRSFJxmrPxw6wzadlc9b93prZIo9WhsS8mp7ENOx9l+pF6PWSOZkW/WH/JZOspm2ugX/KvLqUsXKhZCDkhebM5YJ7GcpU0xFhIayK6B5Kbw2HIrtK0HnQRs7Nrjb8PeDccJWPucoz/TCtPmb6mkd/d5WhHFGp2yVnKBagTBoKo7zpGK6Na/44+Ht5uc8ZO8frukciIMPsf9xCgUT2bBAh3K8LRerj79oC4EULO0pqhq4rkK8p2uMTWBj/vfI0Pmk58QBFk62DhcTLTN5t3J8ztb3nEdG06oVH41cvawBw00BaGCTBdL20l3irv+Vt7TBliL84TgoMV2CD7RcMpmX3GXsytAiIAOuklzgjpsrkDuqqi85tOf3OPfIig3/7+ellJQb93F9x1/X9LUap7z8PafxnZMrpd7GhsdH49V6oAagiIYmNbhla2WXVZjnX75chi5LL14j+D/DS93yCMbadvUA3cjPu8CwKgW+HDP72DrAspUzxmvS+D9MP1XMvnVj9hF1RaFsaasP0bzNiU7HxLnENjDwInFYQbDd188mlUl+zCGSvA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
