travis:
  secure:
    BINSTAR_TOKEN: Tkm+5EaSfiWNWDf6V/HKr8KeU0Q29dQJqhdADh9D24JqSA/vGsLobfeIX20zgQ5hGleWMrgUhhx5J/etSNVXk6NQvjRF9AEScNbSDTX9t9fxjLuTueqixYJrTmBI/zz04nahvPhNUsOeanfiPVTW4WXSGdzqxIQLLlccTIjCNceuh2aAz6M2KXU22HEkEmlcqEKUsejWCmsTxGbQWvvzfrvLk6jwTCASshQ3wBLX0umlDRxeUIdiLP8XngvOVrXcF7i0mggl0tLOC5RU2grQjKVLrctKj1k1PV4kbHrhqy9AIb88mGqYKC5IAC01gmYEVu4oEKnm8mY64bZwkjieK5Jhk1eE7AAO7SAIhW9oFyi5gdvTEEl0p9j3SLPl1+snLIgVD2A9/2cyRELbaIx8pBCy/sAnPGBcovjtc23Ag41+wq3z4muoH8NUC9YnZg79NN4PA1kbogB+iTPlcQOpx/CvSDrsO3v9iSRZAQfFyflMEL0j3kZvqkCeqv9ffOqdRCH9srtQL7chOWH8ROyRpKWeBcg76TuJAMCuzfQxWJ470/vT21PObYfDwYfrc0CvZaRd/t+XwS/VAPQ+gmabPFXhUWEHhBYW31ThXlCdbYVYHyTHIKUygVJkjl8dHmJL2nitSTslrN3ynFHAxCzdPVN8rrct2/eQQm4nYA2AfGg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
